### ISSUE TITLE
Refresh Deletes Existing PR Bots + Restarts ongoing Integration

### ISSUE THREAD

**Issue by ignkarman** [E-B-Smith/xcode-github#10]
Hello,

First off - I love this app, and would love to contribute. 

I noticed when I have a low refresh time (1 minute), My integrations never complete, because the Refresh deletes and then creates new Bots for the existing PRs. Is this expected behavior? I can just turn down my refresh time, but it would be nice to allow bots with ongoing integrations to not get overwritten

**Comment by ignkarman** [comment]
Seems to be an issue with mistaking bots with open PRs for bots that have had their PRs removed.

Relevant code in XGCommand.m

```
  // Check for bots with no PR and delete it:
        for (XGXcodeBot *bot in bots.objectEnumerator) {
            NSString *number = bot.pullRequestNumber;
            if (number && !pullRequests[number]) {
                error = XGDeleteBotWithOptions(options, bot);
                if (error) { returnCode = EX_NOPERM; goto exit; }
            }
        }
```

**Comment by E-B-Smith** [comment]
I'm glad you're finding Xcode-GitHub useful!

A few questions:

Does the bot you use as a template have GitHub set as its source control?

Are bots not created by Xcode-GitHub being deleted too?

**Comment by ignkarman** [comment]
1. Yes - Template Bots are using Github as source control. 
2. No - Only Bots created Xcode-Github are being deleted.

My current work around is commenting out the call to `XGDeleteBotWithOptions` in the code snippet above. I obviously have to delete my bots myself, but it's a better workaround for me. I'd be happy to get in there with the debugger when I find some free moments and try to take a look at why it's not recognizing the bots as having existing PRs.

**Comment by E-B-Smith** [comment]
This isn't happening on my end or I'd fix it right away, obviously.

I wonder if the status your PRs is getting set to something other than 'open'?

https://github.com/E-B-Smith/xcode-github/blob/410bc632cc197aed469562203de34d9715b7964b/XcodeGitHub/XGGitHubPullRequest.m#L135-L138

**Comment by ignkarman** [comment]
This issue no longer occurs for me. Not sure what the root cause of the issue, but if there's not objection, I'm going to close this issue.
